"""
    Polizei Brandenburg API

    Nachrichten, Hochwasser-, Verkehrs- und Waldbrandwarnungen der Polizei Brandenburg  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.polizei_brandenburg.model.pegel_data_inner import PegelDataInner

from deutschland import polizei_brandenburg


class TestPegelDataInner(unittest.TestCase):
    """PegelDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPegelDataInner(self):
        """Test PegelDataInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PegelDataInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
