"""
    Polizei Brandenburg: App

    Polizei Brandenburg Nachrichten, Hochwasser-, Verkehrs- und Waldbrandwarnungen  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.polizei_brandenburg.model.waldbrand_data import WaldbrandData

from deutschland import polizei_brandenburg

globals()["WaldbrandData"] = WaldbrandData
from deutschland.polizei_brandenburg.model.waldbrand import Waldbrand


class TestWaldbrand(unittest.TestCase):
    """Waldbrand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaldbrand(self):
        """Test Waldbrand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Waldbrand()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
