"""
    Polizei Brandenburg API

    Nachrichten, Hochwasser-, Verkehrs- und Waldbrandwarnungen der Polizei Brandenburg  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.polizei_brandenburg.model.waldbrand_data_inner import (
    WaldbrandDataInner,
)

from deutschland import polizei_brandenburg


class TestWaldbrandDataInner(unittest.TestCase):
    """WaldbrandDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaldbrandDataInner(self):
        """Test WaldbrandDataInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WaldbrandDataInner()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
