"""
    Polizei Brandenburg API

    Nachrichten, Hochwasser-, Verkehrs- und Waldbrandwarnungen der Polizei Brandenburg  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.polizei_brandenburg.model.reviere_data_inner import ReviereDataInner

from deutschland import polizei_brandenburg

globals()["ReviereDataInner"] = ReviereDataInner
from deutschland.polizei_brandenburg.model.reviere import Reviere


class TestReviere(unittest.TestCase):
    """Reviere unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReviere(self):
        """Test Reviere"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Reviere()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
